### ISSUE TITLE
forecase[x] issue

### ISSUE THREAD

**Issue by anzhan** [monkeecreate/jquery.simpleWeather#166]
0 doesn't start from today but 2 days ago for some reason. 
I've checked local machine and server time they are both correct. any thoughts?

**Comment by fleeting** [comment]
Looks like Yahoo is having more issues with their API. If you view their developer example, it shows forecast going back a few days instead of it being a five day forecast - https://developer.yahoo.com/weather/. It's not something I have control over. The issue can be reported to Yahoo on their [uservoice](https://yahoo.uservoice.com/forums/207813-us-weather) site.
