### ISSUE TITLE
simpleWeather is not working today

### ISSUE THREAD

**Issue by miamis** [monkeecreate/jquery.simpleWeather#180]
Hello

simpleWeather seems to have big troubles.
It doesn't work anywhere.
What's up ?

**Comment by exhtml** [comment]
Here:
http://stackoverflow.com/questions/34920765/cannot-read-property-channel-of-null-with-simpleweather-js
they explain that:
Yahoo seems to have discontinued the geolocation services needed to find a location based on latitude and longitude. Using simpleWeather's woeid property instead of location still works, though

**Comment by andretf** [comment]
See #174 for solution! Surround lat/log with parentheses.
