### ISSUE TITLE
Is this working

### ISSUE THREAD

**Issue by marekka** [monkeecreate/jquery.simpleWeather#194]
It appears the widget is not working even on your demos?

http://codepen.io/fleeting/pen/xklfq

**Comment by marekka** [comment]
Or here
http://simpleweatherjs.com/

**Comment by KevinBatdorf** [comment]
Also not working for us. Been like this a few days. Thanks!

**Comment by nemchik** [comment]
Yeah I'm having issues with it as well.

**Comment by VitalyNikolaev** [comment]
Really guys? Look next thread, for temporary solution

**Comment by nemchik** [comment]
Thank you for pointing us to look at https://github.com/monkeecreate/jquery.simpleWeather/issues/174 for a solution.

I ended up looking at this issue because I saw no error message indicating what could be going wrong from the JS console or anywhere else. For anyone else who ends up reading this before it gets closed, please go check out https://github.com/monkeecreate/jquery.simpleWeather/issues/174 for a temporary solution (the stuff about line 26).
