### ISSUE TITLE
Receiving wrong night/day images

### ISSUE THREAD

**Issue by luisalves73** [monkeecreate/jquery.simpleWeather#209]
This issue was already opened and closed but I'm experiencing the same and since I'm not a programmer I don't quite got how to solve this.

I'm in the area (Lisbon, Portugal), it's night, and the icon displays sun instead of moon.

I've dumped the updated time and got WED, 10 FEB 2016 2:00 AM WET, so icon should be night, not day.

So something is wrong here with the icon. Aside from the icon, all forecast matches yahoo.

Can you help?

**Comment by luisalves73** [comment]
Ok, problem solved!
The problem is that the content of the css is not distinguishing between uppercase (A) and lowercase (a) so I forced it via css and the problem got solved.
This is what I did:

.icon-27:before { text-transform: lowercase; content: "a"; }

**Comment by fleeting** [comment]
It's because my demo has `text-transform: uppercase;` on the `#weather` div so targets everything inside it. The solution is to add `text-transform: none;` to `i` in the CSS. That will remove the uppercase transform for just the icon element. The demos have been tweaked so much there are most likely other issues, I didn't expect so many people to use the code from it.

**Comment by luisalves73** [comment]
Eheh yeah, people see a snippet of code and BAM! copy! Thanks for the update and for this wonderful widget.
