### ISSUE TITLE
Google PageSpeed Insights

### ISSUE THREAD

**Issue by ingeniumdesign** [monkeecreate/jquery.simpleWeather#246]
Hi, can you optimize the file?

By compressing the file https://query.yahooapis.com/v1/public/yql?format=json&amp;rnd=20164123&amp;diagnostics=true&amp;callback=jQuery22304907789775170386_1464675749494&amp;q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text=%22XXXXX%22)%20and%20u=%22c%22&amp;_=1464675749495"> **62% could be saved**.

Can you load the File asynchronously for Google Page Speed

https://www.lockedowndesign.com/load-google-fonts-asynchronously-for-page-speed/
https://css-tricks.com/thinking-async/

thanks!

**Comment by pmarkoulidakis** [comment]
You could try the async attributre. Its supported on all major browsers. http://caniuse.com/#feat=script-async

**Comment by digitaloutback** [comment]
Unless I'm mistaken, you are confusing 2 different things here - compression requires data from Yahoo to be compressed. Loading files asynchronously refers to the render blocking of a web page.

**Comment by BandonRandon** [comment]
Depending on what you're doing you could also perhaps cache the result of the query locally and only update it when needed. That could save on loading time.

**Comment by digitaloutback** [comment]
Indeed, I localised the data with php get_file_contents and then set a daily cron to update.
-------- Original message --------From: Brooke Dukes <notifications@github.com> Date: 01/10/2017  08:52  (GMT+02:00) To: "monkeecreate/jquery.simpleWeather" <jquery.simpleWeather@noreply.github.com> Cc: digitaloutback <will@digitaloutback.co.uk>, Comment <comment@noreply.github.com> Subject: Re: [monkeecreate/jquery.simpleWeather] Google PageSpeed Insights (#246) 
Depending on what you're doing you could also perhaps cache the result of the query locally and only update it when needed. That could save on loading time.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/monkeecreate/jquery.simpleWeather","title":"monkeecreate/jquery.simpleWeather","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/monkeecreate/jquery.simpleWeather"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BandonRandon in #246: Depending on what you're doing you could also perhaps cache the result of the query locally and only update it when needed. That could save on loading time. "}],"action":{"name":"View Issue","url":"https://github.com/monkeecreate/jquery.simpleWeather/issues/246#issuecomment-333355583"}}}
