### ISSUE TITLE
Weather.sunset not returning full time

### ISSUE THREAD

**Issue by jasonbronson** [monkeecreate/jquery.simpleWeather#248]
Looks like the zero is being chopped off for sunset time of 8:20pm says 

weather.sunset: 8:2 pm

http://codepen.io/jbronson29/pen/KMNOYW

**Comment by fleeting** [comment]
It's coming like that directly from Yahoo - see the [data feed](https://query.yahooapis.com/v1/public/yql?q=select%20astronomy%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Las%20Vegas%2C%20NV%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys). They will need to fix it on their end. Looks like it only happens when it's a zero for some reason. Other times seem to work correctly.
